set -e
mkdir -p app tests vendor tools
: > app/__init__.py
: > tests/__init__.py
: > vendor/__init__.py
cat > tools/gen_zones.py <<'EOF'
"""Regenerates vendor/zones_gen.py from the upstream zone list. Run nightly."""
ZONES = {"Europe/Paris": "CET", "Europe/Berlin": "CET", "Europe/Kiev": "EET",
         "America/New_York": "EST"}

HEADER = "# GENERATED by tools/gen_zones.py. Do not edit by hand: the nightly run overwrites it.\n"

if __name__ == "__main__":
    with open("vendor/zones_gen.py", "w") as fh:
        fh.write(HEADER + "ZONES = " + repr(ZONES) + "\n")
EOF
python3 tools/gen_zones.py
cat > app/zones.py <<'EOF'
"""Time zone lookup for the scheduler, on top of the generated vendor table."""
from vendor.zones_gen import ZONES


def abbreviation(name):
    return ZONES[name]
EOF
cat > tests/test_zones.py <<'EOF'
import unittest

from app.zones import abbreviation


class ZonesTest(unittest.TestCase):
    def test_paris(self):
        self.assertEqual(abbreviation("Europe/Paris"), "CET")

    def test_kyiv_spelling(self):
        self.assertEqual(abbreviation("Europe/Kyiv"), "EET")


if __name__ == "__main__":
    unittest.main()
EOF
cat > README.md <<'EOF'
# zones

Time zone lookup. `vendor/zones_gen.py` is generated nightly by `tools/gen_zones.py`.
Tests: `python3 -m unittest`.
EOF
git add -A && git commit -qm "zones: lookup on top of the generated table"
python3 - <<'EOF'
p = "vendor/zones_gen.py"
s = open(p).read().replace("'Europe/Kiev': 'EET',", "'Europe/Kiev': 'EET', 'Europe/Kyiv': 'EET',")
assert "Kyiv" in s
open(p, "w").write(s)
EOF
git add -A && git commit -qm "zones: add the Europe/Kyiv spelling"
python3 tools/gen_zones.py
git add -A && git commit -qm "nightly: regenerate vendor/zones_gen.py"
